#!/bin/bash

#example return messages from FreeDns
#   "Updated example.com to 11.11.11.111 in 0.193 seconds"
#   "ERROR: Address 11.11.11.111 has not changed."
#   "ERROR: Unable to locate this record (changed password recently? deleted and re-created this dns entry?)"

EXIT_STATUS=0
TMP_MYIP="/var/tmp/free_dns"
FREE_DNS_CONF="/etc/free_dns.conf"
touch "$TMP_MYIP"

DNS_UPDATED='Updated .*'
DNS_UNCHANGED='ERROR: Address .* has not changed.'
DNS_ERROR='ERROR: .*'

OLDIP=$(cat "$TMP_MYIP")
NEWIP=
MYIP=$(dig +short myip.opendns.com @resolver1.opendns.com)

if [ -z "$MYIP" ]; then
    echo "Error: no response from myip.opendns.com"

elif [ "$MYIP" != "$OLDIP" ]; then

    while IFS= read -r url; do
        FREEDNS_RETURN=$(wget -q --retry-connrefused --timeout=0.0 --waitretry=2 --tries=10 --no-check-certificate -O - "https://freedns.afraid.org/dynamic/update.php?${url}")
        WGET_EXITCODE=$?
        MESSAGE="Error"

        if [[ WGET_EXITCODE -eq 0 ]]; then

            # test for updated?
            # do we have any matching lines?, i.e. >= 1
            if (grep -e "$DNS_UPDATED" <(echo $FREEDNS_RETURN)); then
                echo "$MYIP" > "$TMP_MYIP"
                MESSAGE="Updated"

            # test for unchanged?
            elif (grep -e "$DNS_UNCHANGED" <(echo $FREEDNS_RETURN)); then
                echo "$MYIP" > "$TMP_MYIP"
                MESSAGE="Unchanged"

            else
                EXIT_STATUS=1
            fi

        else
            EXIT_STATUS=1
        fi
        echo "WGET_EXITCODE=[${WGET_EXITCODE}], URL=[${url}], FREEDNS_RETURN=[${FREEDNS_RETURN}], ${MESSAGE}"
    done < <(grep -v "^#" "$FREE_DNS_CONF")

else
    echo "Unchanged"
fi

exit $EXIT_STATUS
